"""Episode replay component for the Streamlit dashboard."""

from __future__ import annotations

import numpy as np
import pandas as pd
import streamlit as st

from src.evaluation.backtest import BacktestResults
from src.evaluation.plots import plot_episode_replay

AGENT_DISPLAY = {
    "rl_agent": ("RL Agent", "badge-rl"),
    "bs_delta": ("BS Delta", "badge-bs"),
    "zero_hedge": ("Zero Hedge", "badge-zero"),
}
PLOTLY_CONFIG = {"displayModeBar": True}


def render_episode_replay_page(results: BacktestResults) -> None:
    """
    Render the full Episode Replay page.

    Users select an episode and see a compact summary plus the four-panel
    replay figure generated by the evaluation plotting module.
    """
    episode_ids = sorted(results.episode_df["episode_id"].unique())
    n_episodes = len(episode_ids)

    if n_episodes == 0:
        st.warning("No episodes found in results.")
        return

    col_slider, col_info = st.columns([4, 1])
    with col_slider:
        episode_id = st.slider(
            "Select Episode",
            min_value=int(episode_ids[0]),
            max_value=int(episode_ids[-1]),
            value=int(episode_ids[0]),
            help=(
                "Navigate through individual hedging episodes. Each episode "
                "is one option lifecycle from inception to expiry."
            ),
        )
    with col_info:
        st.metric("Total Episodes", n_episodes)

    ep_data = results.episode_df[results.episode_df["episode_id"] == episode_id]
    _render_episode_summary(ep_data, results)

    st.markdown("---")

    if episode_id not in results.step_df["episode_id"].values:
        st.warning(f"Step-level data not available for episode {episode_id}.")
        return

    fig = plot_episode_replay(results, episode_id=episode_id)
    st.plotly_chart(fig, use_container_width=True, config=PLOTLY_CONFIG)
    _render_percentile_context(episode_id, results)


def _render_episode_summary(ep_data: pd.DataFrame, results: BacktestResults) -> None:
    """Render terminal P&L and transaction cost cards for one episode."""
    if ep_data.empty:
        return

    agents = ep_data["agent_type"].tolist()
    cols = st.columns(max(len(agents), 1))

    for col, (_, row) in zip(cols, ep_data.iterrows(), strict=True):
        agent = row["agent_type"]
        pnl = row["terminal_pnl"]
        cost = row["total_cost"]
        display, badge_class = AGENT_DISPLAY.get(agent, (agent, ""))

        col.markdown(
            f"""
            <div class="metric-card">
                <div class="metric-label">
                    <span class="{badge_class}">{display}</span> - Terminal P&L
                </div>
                <div class="metric-rl-value" style="font-size:1.4rem">
                    {pnl:+.4f}
                </div>
                <div class="metric-baseline-row">
                    <span class="metric-bs-label">Tx cost</span>
                    <span class="metric-bs-value">{cost:.4f}</span>
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )


def _render_percentile_context(episode_id: int, results: BacktestResults) -> None:
    """Show where this episode sits in the RL agent P&L distribution."""
    rl_episodes = results.episode_df[results.episode_df["agent_type"] == "rl_agent"]
    if rl_episodes.empty:
        return

    this_ep = rl_episodes[rl_episodes["episode_id"] == episode_id]
    if this_ep.empty:
        return

    this_pnl = this_ep["terminal_pnl"].values[0]
    all_pnl = rl_episodes["terminal_pnl"].values
    percentile = float(np.mean(all_pnl <= this_pnl) * 100)

    if percentile <= 10:
        context = (
            f"This is a **poor** outcome - bottom {percentile:.0f}th "
            "percentile for the RL agent."
        )
    elif percentile >= 90:
        context = (
            f"This is an **excellent** outcome - top {100 - percentile:.0f}th "
            "percentile for the RL agent."
        )
    else:
        context = (
            f"This is a **typical** outcome - {percentile:.0f}th percentile "
            "for the RL agent."
        )

    st.caption(f"Distribution context: {context}")
